/**
More Information Refer to: https://github.com/IOTechSystems/jenkins-pipelines/tree/master
*/

@Library("devops-libraries") _


pipeline
{
  agent { label 'docker-x86_64' }
  options
  {
    buildDiscarder(logRotator (numToKeepStr: "20"))
    timeout(time: 60, unit: "MINUTES")
    disableConcurrentBuilds()
  }
  stages {
    stage ('Setup Environment') {
      steps {
        script {
          currentBuild.displayName = "EXP-Trigger-App-Configurable with ${env.BRANCH_NAME}: ${env.BUILD_ID}"
          currentBuild.description = "[WARN] This job is for auto trigger only"
          // set default SCAN, ARCHIVE and MANIFESTS
          env.SCAN=true
          env.ARCHIVE=false
          env.MANIFESTS=false
          //if it's a Push event to branch v[0-9]+.[0-9]+-branch, override ARCHIVE and MANIFESTS to true
          common.setupEnv("")
        }
      }
    }
    stage ('Trigger EXP-Build-App-Configurable Job') {
      when { expression { isBuild == "true" } }
      steps {
        script {
          if ("${env.BRANCH_NAME}".startsWith("PR")) {
              env.ASC_BRANCH="${env.CHANGE_TARGET}"
              env.SDK_BRANCH="${env.CHANGE_BRANCH}"
          } else {
              // trigger the corresponding ASC branch job
              env.ASC_BRANCH="${env.BRANCH_NAME}"
              env.SDK_BRANCH="${env.BRANCH_NAME}"
          }
          echo "asc branch: ${ASC_BRANCH} with sdk branch: ${SDK_BRANCH}"
          build job: "EXP-Build-App-Configurable/${ASC_BRANCH}", wait: true, parameters: [
                      string(name: "sdkBranch", value: "${SDK_BRANCH}"),
                      string(name: "ARCH", value: "all"),
                      string(name: "ARCHIVE", value: "${ARCHIVE}"),
                      string(name: "MANIFESTS", value: "${MANIFESTS}")
                     ]
        }
      }
    }
  }
}
